// <auto-generated />
using System;
using HotelQueue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelQueue.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260413045438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelQueue.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelQueue.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HotelQueue.Models.Reservation", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelQueue.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 5600m,
                            RoomNumber = "101",
                            Type = "Standard"
                        },
                        new
                        {
                            RoomId = 2,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 5600m,
                            RoomNumber = "102",
                            Type = "Standard"
                        },
                        new
                        {
                            RoomId = 3,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 5600m,
                            RoomNumber = "103",
                            Type = "Standard"
                        },
                        new
                        {
                            RoomId = 4,
                            Capacity = 3,
                            IsAvailable = true,
                            PricePerNight = 5600m,
                            RoomNumber = "104",
                            Type = "Standard"
                        },
                        new
                        {
                            RoomId = 5,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 5600m,
                            RoomNumber = "105",
                            Type = "Standard"
                        },
                        new
                        {
                            RoomId = 6,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 11200m,
                            RoomNumber = "201",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 7,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 11200m,
                            RoomNumber = "202",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 8,
                            Capacity = 3,
                            IsAvailable = true,
                            PricePerNight = 11200m,
                            RoomNumber = "203",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 9,
                            Capacity = 2,
                            IsAvailable = true,
                            PricePerNight = 11200m,
                            RoomNumber = "204",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 10,
                            Capacity = 3,
                            IsAvailable = true,
                            PricePerNight = 11200m,
                            RoomNumber = "205",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 11,
                            Capacity = 4,
                            IsAvailable = true,
                            PricePerNight = 19600m,
                            RoomNumber = "301",
                            Type = "Suite"
                        },
                        new
                        {
                            RoomId = 12,
                            Capacity = 4,
                            IsAvailable = true,
                            PricePerNight = 19600m,
                            RoomNumber = "302",
                            Type = "Suite"
                        },
                        new
                        {
                            RoomId = 13,
                            Capacity = 4,
                            IsAvailable = true,
                            PricePerNight = 19600m,
                            RoomNumber = "303",
                            Type = "Suite"
                        },
                        new
                        {
                            RoomId = 14,
                            Capacity = 4,
                            IsAvailable = true,
                            PricePerNight = 22400m,
                            RoomNumber = "304",
                            Type = "Suite"
                        },
                        new
                        {
                            RoomId = 15,
                            Capacity = 4,
                            IsAvailable = true,
                            PricePerNight = 22400m,
                            RoomNumber = "305",
                            Type = "Suite"
                        });
                });

            modelBuilder.Entity("HotelQueue.Models.WaitlistEntry", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PreferredCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredRoomType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("WaitlistId");

                    b.HasIndex("CustomerId");

                    b.ToTable("WaitlistEntries");
                });

            modelBuilder.Entity("HotelQueue.Models.Reservation", b =>
                {
                    b.HasOne("HotelQueue.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelQueue.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelQueue.Models.WaitlistEntry", b =>
                {
                    b.HasOne("HotelQueue.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
